CC = gcc

CFLAGS=-g

proj6: proj6.o frac_heap.o
	gcc $^ -o $@

test1: test1.o frac_heap.o
	gcc $^ -o $@

test2: test2.o frac_heap.o
	gcc $^ -o $@

test3: test3.o frac_heap.o
	gcc $^ -o $@

test4: test4.o frac_heap.o
	gcc $^ -o $@

test5: test5.o frac_heap.o
	gcc $^ -o $@

test6: test6.o frac_heap.o
	gcc $^ -o $@

test7: test7.o frac_heap.o
	gcc $^ -o $@
run:
	./proj6

run1:
	./test1

run2:
	./test2

run3:
	./test3

run4:
	./test4

run5:
	./test5

run6:
	./test6

run7:
	./test7

clean:
	rm -f *.o *.out *.lst *~

cleaner:
	rm -f *.o *.out *.lst *~
	rm proj6 test1 test2 test3 test4 test5 test6 test7
